// 배틀이 여는 뱅크 셋의 줄 이름 (DATA.md §2.11 · PARITY §2.24 · §2.26)
//
// `battle_strings` us 368 · `battle_bag` us 2 · `battle_party` us 3 세 뱅크의 줄 순서다. **자리 = 배열 인덱스**이고
// 이름은 디컴프 `res/text/*.json`의 `id`에서 뱅크별 앞가지를 뗀 것이다.
//
// ⚠️ **여기에는 롬에서 읽은 값이 하나도 없다** — `textBanks.ts`의 `BANK_ORDER`와
// 같은 성격이다. 이름의 순서뿐이고, 그 순서가 곧 뱅크의 순서다 (COPYRIGHT.md §6).
//
// 쓰는 자리는 **시험 하나**다 (`ui/battle/romText.test.ts`). 화면이 읽는 번호는
// `ui/battle/romText.ts`가 숫자로 들고 있고, 그 숫자가 여기 이름과 맞는지를
// 그 시험이 잰다 — 그래서 이 표는 앱 묶음에 안 실린다.
//
// ⚠️ **손으로 고치지 않는다.** `pnpm gen:battleStrings`가 다시 만든다.

/** `battle_strings` (us 368) 뱅크 안의 줄 순서. 자리가 곧 줄 번호다 */
export const BATTLE_STRING_ORDER: readonly string[] = [
  'Dummy0', 'PokemonGainedExpPoints', 'PokemonGainedABoostedExpPoints', 'PokemonGrewToLevel',
  'PokemonLearnedMove', 'PokemonIsTryingToLearnMove', 'ButPokemonCantLearnMoreThanFourMoves',
  'DeleteAMoveToMakeRoomForMove', 'PokemonForgotTheMove', 'GiveUpOnLearningTheMove',
  'PokemonDidNotLearnMove', 'UseNextPokemonYesNo', 'PokemonsAttackMissed_Ally',
  'PokemonsAttackMissed_Wild', 'TheAttackOfPokemonMissed_Foe', 'PokemonProtectedItself_Ally',
  'PokemonProtectedItself_Wild', 'PokemonProtectedItself_Foe',
  'PokemonAvoidedDamageByUsingAbility_Ally', 'PokemonAvoidedDamageByUsingAbility_Wild',
  'PokemonAvoidedDamageByUsingAbility_Foe', 'PokemonMakesGroundMovesMissByUsingAbility_Ally',
  'PokemonMakesGroundMovesMissByUsingAbility_Wild',
  'PokemonMakesGroundMovesMissByUsingAbility_Foe', 'PokemonAvoidedTheAttack_Ally',
  'PokemonAvoidedTheAttack_Wild', 'PokemonAvoidedTheAttack_Foe', 'ItDoesntAffectPokemon_Ally',
  'ItDoesntAffectPokemon_Wild', 'ItDoesntAffectPokemon_Foe', 'PokemonFainted_Ally',
  'PokemonFainted_Wild', 'PokemonFainted_Foe', 'PlayerGotMoneyForWinning',
  'PlayerDroppedMoneyInPanic', 'PlayerPaidOutMoneyToTheWinner', 'PlayerIsOutOfUsablePokemon',
  'PlayerBlackedOut', 'BlackedOutDotDotDot', 'PokemonPreventsEscapeWithAbility_Ally',
  'PokemonPreventsEscapeWithAbility_Wild', 'PokemonPreventsEscapeWithAbility_Foe', 'CantEscape',
  'PokemonCantEscape_Ally', 'PokemonCantEscape_Wild', 'PokemonCantEscape_Foe', 'HitXTimes',
  'PokemonFellAsleep_Ally', 'PokemonFellAsleep_Wild', 'PokemonFellAsleep_Foe',
  'PokemonsAbilityMadePokemonFallAsleep_AllyAlly', 'PokemonsAbilityMadePokemonFallAsleep_AllyWild',
  'PokemonsAbilityMadePokemonFallAsleep_AllyFoe', 'PokemonsAbilityMadePokemonFallAsleep_WildAlly',
  'PokemonsAbilityMadePokemonFallAsleep_WildWild', 'PokemonsAbilityMadePokemonFallAsleep_FoeAlly',
  'PokemonsAbilityMadePokemonFallAsleep_FoeFoe', 'PokemonIsAlreadyAsleep_Ally',
  'PokemonIsAlreadyAsleep_Wild', 'PokemonIsAlreadyAsleep_Foe', 'PokemonWasntAffected_Ally',
  'PokemonWasntAffected_Wild', 'PokemonWasntAffected_Foe', 'PokemonWasPoisoned_Ally',
  'PokemonWasPoisoned_Wild', 'PokemonWasPoisoned_Foe', 'PokemonsAbilityPoisonedPokemon_AllyAlly',
  'PokemonsAbilityPoisonedPokemon_AllyWild', 'PokemonsAbilityPoisonedPokemon_AllyFoe',
  'PokemonsAbilityPoisonedPokemon_WildAlly', 'PokemonsAbilityPoisonedPokemon_WildWild',
  'PokemonsAbilityPoisonedPokemon_FoeAlly', 'PokemonsAbilityPoisonedPokemon_FoeFoe',
  'PokemonIsHurtByPoison_Ally', 'PokemonIsHurtByPoison_Wild', 'PokemonIsHurtByPoison_Foe',
  'PokemonIsAlreadyPoisoned_Ally', 'PokemonIsAlreadyPoisoned_Wild', 'PokemonIsAlreadyPoisoned_Foe',
  'PokemonWasBadlyPoisoned_Ally', 'PokemonWasBadlyPoisoned_Wild', 'PokemonWasBadlyPoisoned_Foe',
  'PokemonHadItsEnergyDrained_Ally', 'PokemonHadItsEnergyDrained_Wild',
  'PokemonHadItsEnergyDrained_Foe', 'PokemonWasBurned_Ally', 'PokemonWasBurned_Wild',
  'PokemonWasBurned_Foe', 'PokemonsAbilityBurnedPokemon_AllyAlly',
  'PokemonsAbilityBurnedPokemon_AllyWild', 'PokemonsAbilityBurnedPokemon_AllyFoe',
  'PokemonsAbilityBurnedPokemon_WildAlly', 'PokemonsAbilityBurnedPokemon_WildWild',
  'PokemonsAbilityBurnedPokemon_FoeAlly', 'PokemonsAbilityBurnedPokemon_FoeFoe',
  'PokemonIsHurtByItsBurn_Ally', 'PokemonIsHurtByItsBurn_Wild', 'PokemonIsHurtByItsBurn_Foe',
  'PokemonAlreadyHasABurn_Ally', 'PokemonAlreadyHasABurn_Wild', 'PokemonAlreadyHasABurn_Foe',
  'PokemonWasFrozenSolid_Ally', 'PokemonWasFrozenSolid_Wild', 'PokemonWasFrozenSolid_Foe',
  'PokemonsAbilityFrozePokemonSolid_AllyAlly', 'PokemonsAbilityFrozePokemonSolid_AllyWild',
  'PokemonsAbilityFrozePokemonSolid_AllyFoe', 'PokemonsAbilityFrozePokemonSolid_WildAlly',
  'PokemonsAbilityFrozePokemonSolid_WildWild', 'PokemonsAbilityFrozePokemonSolid_FoeAlly',
  'PokemonsAbilityFrozePokemonSolid_FoeFoe', 'PokemonIsFrozenSolid_Ally',
  'PokemonIsFrozenSolid_Wild', 'PokemonIsFrozenSolid_Foe', 'PokemonThawedOut_Ally',
  'PokemonThawedOut_Wild', 'PokemonThawedOut_Foe', 'PokemonWasDefrostedByMove_Ally',
  'PokemonWasDefrostedByMove_Wild', 'PokemonWasDefrostedByMove_Foe',
  'PokemonIsParalyzedItMayBeUnableToMove_Ally', 'PokemonIsParalyzedItMayBeUnableToMove_Wild',
  'PokemonIsParalyzedItMayBeUnableToMove_Foe', 'PokemonsAbilityParalyzedPokemon_AllyAlly',
  'PokemonsAbilityParalyzedPokemon_AllyWild', 'PokemonsAbilityParalyzedPokemon_AllyFoe',
  'PokemonsAbilityParalyzedPokemon_WildAlly', 'PokemonsAbilityParalyzedPokemon_WildWild',
  'PokemonsAbilityParalyzedPokemon_FoeAlly', 'PokemonsAbilityParalyzedPokemon_FoeFoe',
  'PokemonIsParalyzedItCantMove_Ally', 'PokemonIsParalyzedItCantMove_Wild',
  'PokemonIsParalyzedItCantMove_Foe', 'PokemonIsAlreadyParalyzed_Ally',
  'PokemonIsAlreadyParalyzed_Wild', 'PokemonIsAlreadyParalyzed_Foe',
  'PokemonWasHealedOfParalysis_Ally', 'PokemonWasHealedOfParalysis_Wild',
  'PokemonWasHealedOfParalysis_Foe', 'PokemonsDreamWasEaten_Ally', 'PokemonsDreamWasEaten_Wild',
  'PokemonsDreamWasEaten_Foe', 'PokemonsStatWontGoHigher_Ally', 'PokemonsStatWontGoHigher_Wild',
  'PokemonsStatWontGoHigher_Foe', 'PokemonsStatWontGoLower_Ally', 'PokemonsStatWontGoLower_Wild',
  'PokemonsStatWontGoLower_Foe', '00148', '00149', 'PokemonIsConfused_Ally',
  'PokemonIsConfused_Wild', 'PokemonIsConfused_Foe', 'PokemonSnappedOutOfConfusion_Ally',
  'PokemonSnappedOutOfConfusion_Wild', 'PokemonSnappedOutOfConfusion_Foe',
  'PokemonBecameConfused_Ally', 'PokemonBecameConfused_Wild', 'PokemonBecameConfused_Foe',
  'PokemonIsAlreadyConfused_Ally', 'PokemonIsAlreadyConfused_Wild', 'PokemonIsAlreadyConfused_Foe',
  'PokemonFellInLove_Ally', 'PokemonFellInLove_Wild', 'PokemonFellInLove_Foe',
  'PokemonIsInLoveWithPokemon_AllyAlly', 'PokemonIsInLoveWithPokemon_AllyWild',
  'PokemonIsInLoveWithPokemon_AllyFoe', 'PokemonIsInLoveWithPokemon_WildAlly',
  'PokemonIsInLoveWithPokemon_WildWild', 'PokemonIsInLoveWithPokemon_FoeAlly',
  'PokemonIsInLoveWithPokemon_FoeFoe', 'PokemonIsImmobilizedByLove_Ally',
  'PokemonIsImmobilizedByLove_Wild', 'PokemonIsImmobilizedByLove_Foe', 'PokemonWasBlownAway_Ally',
  'PokemonWasBlownAway_Wild', 'PokemonWasBlownAway_Foe', 'PokemonTransformedIntoType_Ally',
  'PokemonTransformedIntoType_Wild', 'PokemonTransformedIntoType_Foe', 'PokemonFlinched_Ally',
  'PokemonFlinched_Wild', 'PokemonFlinched_Foe', 'PokemonRegainedHealth_Ally',
  'PokemonRegainedHealth_Wild', 'PokemonRegainedHealth_Foe', 'PokemonsHPIsFull_Ally',
  'PokemonsHPIsFull_Wild', 'PokemonsHPIsFull_Foe', 'MoveRaisedYourTeamsSpecialDefense',
  'TheFoesMoveRaisedItsTeamsSpecialDefense', 'MoveRaisedYourTeamsSpecialDefenseSlightly',
  'TheFoesMoveRaisedItsTeamsSpecialDefenseSlightly', 'MoveRaisedYourTeamsDefense',
  'TheFoesMoveRaisedItsTeamsDefense', 'MoveRaisedYourTeamsDefenseSlightly',
  'TheFoesMoveRaisedItsTeamsDefenseSlightly', 'YourTeamBecameCloakedInAMysticalVeil',
  'TheFoesTeamBecameCloakedInAMysticalVeil', 'PokemonIsProtectedBySafeguard_Ally',
  'PokemonIsProtectedBySafeguard_Wild', 'PokemonIsProtectedBySafeguard_Foe',
  'YourTeamIsNoLongerProtectedBySafeguard', 'TheFoeIsNoLongerProtectedBySafeguard',
  'PokemonWentToSleep_Ally', 'PokemonWentToSleep_Wild', 'PokemonWentToSleep_Foe',
  'PokemonSleptAndBecameHealthy_Ally', 'PokemonSleptAndBecameHealthy_Wild',
  'PokemonSleptAndBecameHealthy_Foe', 'PokemonWhippedUpAWhirlwind_Ally',
  'PokemonWhippedUpAWhirlwind_Wild', 'PokemonWhippedUpAWhirlwind_Foe', 'PokemonAbsorbedLight_Ally',
  'PokemonAbsorbedLight_Wild', 'PokemonAbsorbedLight_Foe', 'PokemonTuckedInItsHead_Ally',
  'PokemonTuckedInItsHead_Wild', 'PokemonTuckedInItsHead_Foe',
  'PokemonBecameCloakedInAHarshLight_Ally', 'PokemonBecameCloakedInAHarshLight_Wild',
  'PokemonBecameCloakedInAHarshLight_Foe', 'PokemonFlewUpHigh_Ally', 'PokemonFlewUpHigh_Wild',
  'PokemonFlewUpHigh_Foe', 'PokemonBurrowedItsWayUnderTheGround_Ally',
  'PokemonBurrowedItsWayUnderTheGround_Wild', 'PokemonBurrowedItsWayUnderTheGround_Foe',
  'PokemonHidUnderwater_Ally', 'PokemonHidUnderwater_Wild', 'PokemonHidUnderwater_Foe',
  'PokemonSprangUp_Ally', 'PokemonSprangUp_Wild', 'PokemonSprangUp_Foe',
  'PokemonWasSqueezedByPokemon_AllyAlly', 'PokemonWasSqueezedByPokemon_AllyWild',
  'PokemonWasSqueezedByPokemon_AllyFoe', 'PokemonWasSqueezedByPokemon_WildAlly',
  'PokemonWasSqueezedByPokemon_WildWild', 'PokemonWasSqueezedByPokemon_FoeAlly',
  'PokemonWasSqueezedByPokemon_FoeFoe', 'PokemonWasTrappedInAVortex_Ally',
  'PokemonWasTrappedInAVortex_Wild', 'PokemonWasTrappedInAVortex_Foe',
  'PokemonWasTrappedBySandTomb_Ally', 'PokemonWasTrappedBySandTomb_Wild',
  'PokemonWasTrappedBySandTomb_Foe', 'PokemonWasWrappedByPokemon_AllyAlly',
  'PokemonWasWrappedByPokemon_AllyWild', 'PokemonWasWrappedByPokemon_AllyFoe',
  'PokemonWasWrappedByPokemon_WildAlly', 'PokemonWasWrappedByPokemon_WildWild',
  'PokemonWasWrappedByPokemon_FoeAlly', 'PokemonWasWrappedByPokemon_FoeFoe',
  'PokemonClampedPokemon_AllyAlly', 'PokemonClampedPokemon_WildAlly',
  'PokemonClampedPokemon_FoeAlly', 'PokemonClampedPokemon_AllyWild',
  'PokemonClampedPokemon_WildWild', 'PokemonClampedPokemon_AllyFoe',
  'PokemonClampedPokemon_FoeFoe', 'PokemonIsHurtByMove_Ally', 'PokemonIsHurtByMove_Wild',
  'PokemonIsHurtByMove_Foe', 'PokemonWasFreedFromMove_Ally', 'PokemonWasFreedFromMove_Wild',
  'PokemonWasFreedFromMove_Foe', 'PokemonKeptGoingAndCrashed_Ally',
  'PokemonKeptGoingAndCrashed_Wild', 'PokemonKeptGoingAndCrashed_Foe',
  'YourTeamBecameShroudedInMist', 'TheFoesTeamBecameShroudedInMist',
  'PokemonIsProtectedByMist_Ally', 'PokemonIsProtectedByMist_Wild', 'PokemonIsProtectedByMist_Foe',
  'PokemonIsGettingPumped_Ally', 'PokemonIsGettingPumped_Wild', 'PokemonIsGettingPumped_Foe',
  'PokemonIsHitWithRecoil_Ally', 'PokemonIsHitWithRecoil_Wild', 'PokemonIsHitWithRecoil_Foe',
  'PokemonProtectedItself2_Ally', 'PokemonProtectedItself2_Wild', 'PokemonProtectedItself2_Foe',
  'PokemonIsBuffetedByTheWeather_Ally', 'PokemonIsBuffetedByTheWeather_Wild',
  'PokemonIsBuffetedByTheWeather_Foe', 'YourTeamsMoveEffectWoreOff', 'TheFoesMoveEffectWoreOff',
  'PokemonWasSeeded_Ally', 'PokemonWasSeeded_Wild', 'PokemonWasSeeded_Foe',
  'PokemonEvadedTheAttack_Ally', 'PokemonEvadedTheAttack_Wild', 'PokemonEvadedTheAttack_Foe',
  'PokemonsHealthIsSappedByLeechSeed_Ally', 'PokemonsHealthIsSappedByLeechSeed_Wild',
  'PokemonsHealthIsSappedByLeechSeed_Foe', 'PokemonIsFastAsleep_Ally', 'PokemonIsFastAsleep_Wild',
  'PokemonIsFastAsleep_Foe', 'PokemonWokeUp_Ally', 'PokemonWokeUp_Wild', 'PokemonWokeUp_Foe',
  'TheUproarWokeUpThePokemon_Ally', 'TheUproarWokeUpPokemon_Wild', 'TheUproarWokeUpPokemon_Foe',
  'PokemonCausedAnUproar_Ally', 'PokemonCausedAnUproar_Wild', 'PokemonCausedAnUproar_Foe',
  'PokemonIsMakingAnUproar_Ally', 'PokemonIsMakingAnUproar_Wild', 'PokemonIsMakingAnUproar_Foe',
  'PokemonCalmedDown_Ally', 'PokemonCalmedDown_Wild', 'PokemonCalmedDown_Foe',
  'PokemonStockpiledX_Ally', 'PokemonStockpiledX_Wild', 'PokemonStockpiledX_Foe',
  'PokemonCantStockpileAnyMore_Ally', 'PokemonCantStockpileAnyMore_Wild',
  'PokemonCantStockpileAnyMore_Foe', 'ButPokemonCantSleepInAnUproar_Ally',
  'ButPokemonCantSleepInAnUproar_Wild', 'ButPokemonCantSleepInAnUproar_Foe',
  'ButTheUproarKeptPokemonAwake_Ally', 'ButTheUproarKeptPokemonAwake_Wild',
  'ButTheUproarKeptPokemonAwake_Foe', 'PokemonStayedAwakeBecauseOfItsAbility_Ally',
  'PokemonStayedAwakeBecauseOfItsAbility_Wild', 'PokemonStayedAwakeBecauseOfItsAbility_Foe',
  'PokemonIsStoringEnergy_Ally', 'PokemonIsStoringEnergy_Wild', 'PokemonIsStoringEnergy_Foe',
  'PokemonUnleashedEnergy_Ally', 'PokemonUnleashedEnergy_Wild', 'PokemonUnleashedEnergy_Foe',
  'PokemonBecameConfusedDueToFatigue_Ally', 'PokemonBecameConfusedDueToFatigue_Wild',
  'PokemonBecameConfusedDueToFatigue_Foe', 'PlayerPickedUpMoney', 'PokemonIsUnaffected_Ally',
  'PokemonIsUnaffected_Wild', 'PokemonIsUnaffected_Foe', 'PokemonTransformedIntoPokemon_AllyAlly',
  'PokemonTransformedIntoPokemon_WildAlly', 'PokemonTransformedIntoPokemon_FoeAlly',
  'PokemonMadeASubstitute_Ally', 'PokemonMadeASubstitute_Wild', 'PokemonMadeASubstitute_Foe',
  'PokemonAlreadyHasASubstitute_Ally', 'PokemonAlreadyHasASubstitute_Wild',
  'PokemonAlreadyHasASubstitute_Foe', 'TheSubstituteTookDamageForPokemon_Ally',
  'TheSubstituteTookDamageForPokemon_Wild', 'TheSubstituteTookDamageForPokemon_Foe',
  'PokemonsSubstituteFaded_Ally', 'PokemonsSubstituteFaded_Wild', 'PokemonsSubstituteFaded_Foe',
  'PokemonMustRecharge_Ally', 'PokemonMustRecharge_Wild', 'PokemonMustRecharge_Foe',
  'PokemonsRageIsBuilding_Ally', 'PokemonsRageIsBuilding_Wild', 'PokemonsRageIsBuilding_Foe',
  'PokemonsMoveWasDisabled_Ally', 'PokemonsMoveWasDisabled_Wild', 'PokemonsMoveWasDisabled_Foe',
  'PokemonIsNoLongerDisabled_Ally', 'PokemonIsNoLongerDisabled_Wild',
  'PokemonIsNoLongerDisabled_Foe', 'PokemonReceivedAnEncore_Ally', 'PokemonReceivedAnEncore_Wild',
  'PokemonReceivedAnEncore_Foe', 'PokemonsEncoreEnded_Ally', 'PokemonsEncoreEnded_Wild',
  'PokemonsEncoreEnded_Foe', 'PokemonTookAimAtPokemon_AllyAlly',
  'PokemonTookAimAtPokemon_AllyWild', 'PokemonTookAimAtPokemon_AllyFoe',
  'PokemonTookAimAtPokemon_WildAlly', 'PokemonTookAimAtPokemon_WildWild',
  'PokemonTookAimAtPokemon_FoeAlly', 'PokemonTookAimAtPokemon_FoeFoe', 'PokemonSketchedMove_Ally',
  'PokemonSketchedMove_Wild', 'PokemonSketchedMove_Foe', 'PokemonIsTryingToTakeItsFoeWithIt_Ally',
  'PokemonIsTryingToTakeItsFoeWithIt_Wild', 'PokemonIsTryingToTakeItsFoeWithIt_Foe',
  'PokemonTookPokemonDownWithIt_AllyAlly', 'PokemonTookPokemonDownWithIt_AllyWild',
  'PokemonTookPokemonDownWithIt_AllyFoe', 'PokemonTookPokemonDownWithIt_WildAlly',
  'PokemonTookPokemonDownWithIt_WildWild', 'PokemonTookPokemonDownWithIt_FoeAlly',
  'PokemonTookPokemonDownWithIt_FoeFoe', 'ItReducedThePPOfPokemonsMoveByX_Ally',
  'ItReducedThePPOfPokemonsMoveByX_Wild', 'ItReducedThePPOfPokemonsMoveByX_Foe',
  'PokemonStolePokemonsItem_AllyAlly', 'PokemonStolePokemonsItem_AllyWild',
  'PokemonStolePokemonsItem_AllyFoe', 'PokemonStolePokemonsItem_WildAlly',
  'PokemonStolePokemonsItem_WildWild', 'PokemonStolePokemonsItem_FoeAlly',
  'PokemonStolePokemonsItem_FoeFoe', 'PokemonCanNoLongerEscape_Ally',
  'PokemonCanNoLongerEscape_Wild', 'PokemonCanNoLongerEscape_Foe',
  'PokemonBeganHavingANightmare_Ally', 'PokemonBeganHavingANightmare_Wild',
  'PokemonBeganHavingANightmare_Foe', 'PokemonIsLockedInANightmare_Ally',
  'PokemonIsLockedInANightmare_Wild', 'PokemonIsLockedInANightmare_Foe',
  'PokemonCutItsOwnHPAndLaidACurseOnPokemon_AllyAlly',
  'PokemonCutItsOwnHPAndLaidACurseOnPokemon_AllyWild',
  'PokemonCutItsOwnHPAndLaidACurseOnPokemon_AllyFoe',
  'PokemonCutItsOwnHPAndLaidACurseOnPokemon_WildAlly',
  'PokemonCutItsOwnHPAndLaidACurseOnPokemon_WildWild',
  'PokemonCutItsOwnHPAndLaidACurseOnPokemon_FoeAlly',
  'PokemonCutItsOwnHPAndLaidACurseOnPokemon_FoeFoe', 'PokemonIsAfflictedByTheCurse_Ally',
  'PokemonIsAfflictedByTheCurse_Wild', 'PokemonIsAfflictedByTheCurse_Foe',
  'SpikesWereScatteredAllAroundYourTeamsFeet', 'SpikesWereScatteredAllAroundTheFeetOfTheFoesTeam',
  'PokemonIsHurtByTheSpikes_Ally', 'PokemonIsHurtByTheSpikes_Wild', 'PokemonIsHurtByTheSpikes_Foe',
  'PokemonIdentifiedPokemon_AllyAlly', 'PokemonIdentifiedPokemon_AllyWild',
  'PokemonIdentifiedPokemon_AllyFoe', 'PokemonIdentifiedPokemon_WildAlly',
  'PokemonIdentifiedPokemon_WildWild', 'PokemonIdentifiedPokemon_FoeAlly',
  'PokemonIdentifiedPokemon_FoeFoe', 'PokemonsPerishCountFellToX_Ally',
  'PokemonsPerishCountFellToX_Wild', 'PokemonsPerishCountFellToX_Foe', 'PokemonBracedItself_Ally',
  'PokemonBracedItself_Wild', 'PokemonBracedItself_Foe', 'PokemonEnduredTheHit_Ally',
  'PokemonEnduredTheHit_Wild', 'PokemonEnduredTheHit_Foe', 'MagnitudeX',
  'PokemonCutItsOwnHPAndMaximizedItsAttack_Ally', 'PokemonCutItsOwnHPAndMaximizedItsAttack_Wild',
  'PokemonCutItsOwnHPAndMaximizedItsAttack_Foe', 'PokemonCopiedPokemonsStatChanges_AllyAlly',
  'PokemonCopiedPokemonsStatChanges_AllyWild', 'PokemonCopiedPokemonsStatChanges_AllyFoe',
  'PokemonCopiedPokemonsStatChanges_WildAlly', 'PokemonCopiedPokemonsStatChanges_WildWild',
  'PokemonCopiedPokemonsStatChanges_FoeAlly', 'PokemonCopiedPokemonsStatChanges_FoeFoe',
  'PokemonGotFreeOfPokemonsMove_AllyAlly', 'PokemonGotFreeOfPokemonsMove_AllyWild',
  'PokemonGotFreeOfPokemonsMove_AllyFoe', 'PokemonGotFreeOfPokemonsMove_WildAlly',
  'PokemonGotFreeOfPokemonsMove_WildWild', 'PokemonGotFreeOfPokemonsMove_FoeAlly',
  'PokemonGotFreeOfPokemonsMove_FoeFoe', 'PokemonBlewAwayHazards_Ally',
  'PokemonBlewAwayHazards_Wild', 'PokemonBlewAwayHazards_Foe', 'PokemonFledFromBattle_Ally',
  'PokemonFledFromBattle_Wild', 'PokemonFledFromBattle_Foe', 'PokemonForesawAnAttack_Ally',
  'PokemonForesawAnAttack_Wild', 'PokemonForesawAnAttack_Foe', 'PokemonTookTheMoveAttack_Ally',
  'PokemonTookTheMoveAttack_Wild', 'PokemonTookTheMoveAttack_Foe',
  'PokemonChoseMoveAsItsDestiny_Ally', 'PokemonChoseMoveAsItsDestiny_Wild',
  'PokemonChoseMoveAsItsDestiny_Foe', 'PokemonsBeatUpAttack_Ally', 'PokemonsBeatUpAttack_Wild',
  'PokemonsBeatUpAttack_Foe', 'PokemonBecameTheCenterOfAttention_Ally',
  'PokemonBecameTheCenterOfAttention_Wild', 'PokemonBecameTheCenterOfAttention_Foe',
  'PokemonBeganChargingPower_Ally', 'PokemonBeganChargingPower_Wild',
  'PokemonBeganChargingPower_Foe', 'MoveTurnedIntoMove', 'PokemonsStatusReturnedToNormal_Ally',
  'PokemonsStatusReturnedToNormal_Wild', 'PokemonsStatusReturnedToNormal_Foe',
  'PokemonWasSubjectedToTorment_Ally', 'PokemonWasSubjectedToTorment_Wild',
  'PokemonWasSubjectedToTorment_Foe', 'PokemonIsTighteningItsFocus_Ally',
  'PokemonIsTighteningItsFocus_Wild', 'PokemonIsTighteningItsFocus_Foe',
  'PokemonFellForTheTaunt_Ally', 'PokemonFellForTheTaunt_Wild', 'PokemonFellForTheTaunt_Foe',
  'PokemonIsReadyToHelpPokemon_AllyAlly', 'PokemonIsReadyToHelpPokemon_AllyWild',
  'PokemonIsReadyToHelpPokemon_AllyFoe', 'PokemonIsReadyToHelpPokemon_WildAlly',
  'PokemonIsReadyToHelpPokemon_WildWild', 'PokemonIsReadyToHelpPokemon_FoeAlly',
  'PokemonIsReadyToHelpPokemon_FoeFoe', 'PokemonSwitchedItemsWithItsTarget_Ally',
  'PokemonSwitchedItemsWithItsTarget_Wild', 'PokemonSwitchedItemsWithItsTarget_Foe',
  'PokemonObtainedOneItem_Ally', 'PokemonObtainedOneItem_Wild', 'PokemonObtainedOneItem_Foe',
  'PokemonObtainedOneItemPokemonObtainedOneItem_AllyAlly',
  'PokemonObtainedOneItemPokemonObtainedOneItem_AllyWild',
  'PokemonObtainedOneItemPokemonObtainedOneItem_AllyFoe',
  'PokemonObtainedOneItemPokemonObtainedOneItem_WildAlly',
  'PokemonObtainedOneItemPokemonObtainedOneItem_WildWild',
  'PokemonObtainedOneItemPokemonObtainedOneItem_FoeAlly',
  'PokemonObtainedOneItemPokemonObtainedOneItem_FoeFoe', 'PokemonCopiedPokemonsAbility_AllyAlly',
  'PokemonCopiedPokemonsAbility_AllyWild', 'PokemonCopiedPokemonsAbility_AllyFoe',
  'PokemonCopiedPokemonsAbility_WildAlly', 'PokemonCopiedPokemonsAbility_WildWild',
  'PokemonCopiedPokemonsAbility_FoeAlly', 'PokemonCopiedPokemonsAbility_FoeFoe',
  'PokemonMadeAWish_Ally', 'PokemonMadeAWish_Wild', 'PokemonMadeAWish_Foe',
  'PokemonsWishCameTrue_Ally', 'PokemonsWishCameTrue_Wild', 'PokemonsWishCameTrue_Foe',
  'PokemonPlantedItsRoots_Ally', 'PokemonPlantedItsRoots_Wild', 'PokemonPlantedItsRoots_Foe',
  'PokemonAbsorbedWithItsRoots_Ally', 'PokemonAbsorbedWithItsRoots_Wild',
  'PokemonAbsorbedWithItsRoots_Foe', 'PokemonAnchoredItselfWithItsRoots_Ally',
  'PokemonAnchoredItselfWithItsRoots_Wild', 'PokemonAnchoredItselfWithItsRoots_Foe',
  'PokemonMadePokemonDrowsy_AllyAlly', 'PokemonMadePokemonDrowsy_AllyWild',
  'PokemonMadePokemonDrowsy_AllyFoe', 'PokemonMadePokemonDrowsy_WildAlly',
  'PokemonMadePokemonDrowsy_WildWild', 'PokemonMadePokemonDrowsy_FoeAlly',
  'PokemonMadePokemonDrowsy_FoeFoe', 'PokemonKnockedOffPokemonsItem_AllyAlly',
  'PokemonKnockedOffPokemonsItem_AllyWild', 'PokemonKnockedOffPokemonsItem_AllyFoe',
  'PokemonKnockedOffPokemonsItem_WildAlly', 'PokemonKnockedOffPokemonsItem_WildWild',
  'PokemonKnockedOffPokemonsItem_FoeAlly', 'PokemonKnockedOffPokemonsItem_FoeFoe',
  'PokemonSwappedAbilitiesWithItsTarget_Ally', 'PokemonSwappedAbilitiesWithItsTarget_Wild',
  'PokemonSwappedAbilitiesWithItsTarget_Foe', 'PokemonSealedTheOpponentsMoves_Ally',
  'PokemonSealedTheOpponentsMoves_Wild', 'PokemonSealedTheOpponentsMoves_Foe',
  'PokemonWantsTheFoeToBearAGrudge_Ally', 'PokemonWantsTheFoeToBearAGrudge_Wild',
  'PokemonWantsTheFoeToBearAGrudge_Foe', 'PokemonsMoveLostAllItsPPDueToTheGrudge_Ally',
  'PokemonsMoveLostAllItsPPDueToTheGrudge_Wild', 'PokemonsMoveLostAllItsPPDueToTheGrudge_Foe',
  'PokemonShroudedItselfWithMagicCoat_Ally', 'PokemonShroudedItselfWithMagicCoat_Wild',
  'PokemonShroudedItselfWithMagicCoat_Foe', 'PokemonsMoveWasBouncedBackByMagicCoat_Ally',
  'PokemonsMoveWasBouncedBackByMagicCoat_Wild', 'PokemonsMoveWasBouncedBackByMagicCoat_Foe',
  'PokemonWaitsForATargetToMakeAMove_Ally', 'PokemonWaitsForATargetToMakeAMove_Wild',
  'PokemonWaitsForATargetToMakeAMove_Foe', 'PokemonSnatchedPokemonsMove_AllyAlly',
  'PokemonSnatchedPokemonsMove_AllyWild', 'PokemonSnatchedPokemonsMove_AllyFoe',
  'PokemonSnatchedPokemonsMove_WildAlly', 'PokemonSnatchedPokemonsMove_WildWild',
  'PokemonSnatchedPokemonsMove_FoeAlly', 'PokemonSnatchedPokemonsMove_FoeFoe',
  'ElectricitysPowerWasWeakened', 'FirePowerWasWeakened', 'PokemonFoundOneItem_Ally',
  'PokemonFoundOneItem_Wild', 'PokemonFoundOneItem_Foe', 'ASoothingAromaWaftedThroughTheArea',
  'ItemsCantBeUsedHere', 'ForPokemonTheItemWasFlavor_Ally', 'ForPokemonTheItemWasFlavor_Wild',
  'ForPokemonTheItemWasFlavor_Foe', 'PokemonUsedTheItemToGetPumped_Ally',
  'PokemonUsedTheItemToGetPumped_Wild', 'PokemonUsedTheItemToGetPumped_Foe',
  'PokemonLostItsFocusAndCouldntMove_Ally', 'PokemonLostItsFocusAndCouldntMove_Wild',
  'PokemonLostItsFocusAndCouldntMove_Foe', 'PokemonWasDraggedOut_Ally',
  'PokemonWasDraggedOut_Wild', 'PokemonWasDraggedOut_Foe', 'ItShatteredTheBarrier',
  'ButItHadNoEffect', 'PokemonHasNoMovesLeft', 'PokemonsMoveIsDisabled_Ally',
  'PokemonsMoveIsDisabled_Wild', 'PokemonsMoveIsDisabled_Foe',
  'PokemonCantUseTheSameMoveTwiceInARowDueToTheTorment', 'PokemonCantUseMoveAfterTheTaunt_Ally',
  'PokemonCantUseMoveAfterTheTaunt_Wild', 'PokemonCantUseMoveAfterTheTaunt_Foe',
  'PokemonCantUseTheSealedMove_Ally', 'PokemonCantUseTheSealedMove_Wild',
  'PokemonCantUseTheSealedMove_Foe', 'PokemonsAbilityMadeItRain_Ally',
  'PokemonsAbilityMadeItRain_Wild', 'PokemonsAbilityMadeItRain_Foe',
  'PokemonsAbilityRaisedItsStat_Ally', 'PokemonsAbilityRaisedItsStat_Wild',
  'PokemonsAbilityRaisedItsStat_Foe', 'PokemonWasProtectedByAbility_Ally',
  'PokemonWasProtectedByAbility_Wild', 'PokemonWasProtectedByAbility_Foe',
  'PokemonsAbilityPreventsPokemonFromUsingMove_AllyAlly',
  'PokemonsAbilityPreventsPokemonFromUsingMove_AllyWild',
  'PokemonsAbilityPreventsPokemonFromUsingMove_AllyFoe',
  'PokemonsAbilityPreventsPokemonFromUsingMove_WildAlly',
  'PokemonsAbilityPreventsPokemonFromUsingMove_WildWild',
  'PokemonsAbilityPreventsPokemonFromUsingMove_FoeAlly',
  'PokemonsAbilityPreventsPokemonFromUsingMove_FoeFoe', 'PokemonRestoredHPUsingItsAbility_Ally',
  'PokemonRestoredHPUsingItsAbility_Wild', 'PokemonRestoredHPUsingItsAbility_Foe',
  'PokemonsAbilityMadeMoveUseless_Ally', 'PokemonsAbilityMadeMoveUseless_Wild',
  'PokemonsAbilityMadeMoveUseless_Foe', 'PokemonsAbilityMadeItType_Ally',
  'PokemonsAbilityMadeItType_Wild', 'PokemonsAbilityMadeItType_Foe',
  'PokemonsAbilityPreventsParalysis_Ally', 'PokemonsAbilityPreventsParalysis_Wild',
  'PokemonsAbilityPreventsParalysis_Foe', 'PokemonsAbilityPreventsRomance_Ally',
  'PokemonsAbilityPreventsRomance_Wild', 'PokemonsAbilityPreventsRomance_Foe',
  'PokemonsAbilityPreventsPoisoning_Ally', 'PokemonsAbilityPreventsPoisoning_Wild',
  'PokemonsAbilityPreventsPoisoning_Foe', 'PokemonsAbilityPreventsConfusion_Ally',
  'PokemonsAbilityPreventsConfusion_Wild', 'PokemonsAbilityPreventsConfusion_Foe',
  'PokemonsAbilityRaisedThePowerOfItsFireTypeMoves_Ally',
  'PokemonsAbilityRaisedThePowerOfItsFireTypeMoves_Wild',
  'PokemonsAbilityRaisedThePowerOfItsFireTypeMoves_Foe', 'PokemonAnchorsItselfWithAbility_Ally',
  'PokemonAnchorsItselfWithAbility_Wild', 'PokemonAnchorsItselfWithAbility_Foe',
  'PokemonsAbilityCutsPokemonsStat_AllyAlly', 'PokemonsAbilityCutsPokemonsStat_AllyWild',
  'PokemonsAbilityCutsPokemonsStat_AllyFoe', 'PokemonsAbilityCutsPokemonsStat_WildAlly',
  'PokemonsAbilityCutsPokemonsStat_WildWild', 'PokemonsAbilityCutsPokemonsStat_FoeAlly',
  'PokemonsAbilityCutsPokemonsStat_FoeFoe', 'PokemonsAbilityPreventsStatLoss_Ally',
  'PokemonsAbilityPreventsStatLoss_Wild', 'PokemonsAbilityPreventsStatLoss_Foe',
  'PokemonsAbilityHurtPokemon_AllyAlly', 'PokemonsAbilityHurtPokemon_AllyWild',
  'PokemonsAbilityHurtPokemon_AllyFoe', 'PokemonsAbilityHurtPokemon_WildAlly',
  'PokemonsAbilityHurtPokemon_WildWild', 'PokemonsAbilityHurtPokemon_FoeAlly',
  'PokemonsAbilityHurtPokemon_FoeFoe', 'PokemonTracedPokemonsAbility_AllyAlly',
  'PokemonTracedPokemonsAbility_AllyWild', 'PokemonTracedPokemonsAbility_AllyFoe',
  'PokemonTracedPokemonsAbility_WildAlly', 'PokemonTracedPokemonsAbility_WildWild',
  'PokemonTracedPokemonsAbility_FoeAlly', 'PokemonTracedPokemonsAbility_FoeFoe',
  'PokemonsAbilityPreventsBurns_Ally', 'PokemonsAbilityPreventsBurns_Wild',
  'PokemonsAbilityPreventsBurns_Foe', 'PokemonsAbilityBlocksMove_Ally',
  'PokemonsAbilityBlocksMove_Wild', 'PokemonsAbilityBlocksMove_Foe', '00692', '00693', '00694',
  'PokemonsAbilityWhippedUpASandstorm_Ally', 'PokemonsAbilityWhippedUpASandstorm_Wild',
  'PokemonsAbilityWhippedUpASandstorm_Foe', 'PokemonsAbilityIntensifiedTheSunsRays_Ally',
  'PokemonsAbilityIntensifiedTheSunsRays_Wild', 'PokemonsAbilityIntensifiedTheSunsRays_Foe',
  'PokemonsAbilityWhippedUpAHailstorm_Ally', 'PokemonsAbilityWhippedUpAHailstorm_Wild',
  'PokemonsAbilityWhippedUpAHailstorm_Foe', 'PokemonsAbilityPreventsBufferStatLoss', '00705',
  '00706', 'PokemonsAbilityInfatuatedPokemon_AllyAlly',
  'PokemonsAbilityInfatuatedPokemon_AllyWild', 'PokemonsAbilityInfatuatedPokemon_AllyFoe',
  'PokemonsAbilityInfatuatedPokemon_WildAlly', 'PokemonsAbilityInfatuatedPokemon_WildWild',
  'PokemonsAbilityInfatuatedPokemon_FoeAlly', 'PokemonsAbilityInfatuatedPokemon_FoeFoe',
  'PokemonsAbilityMadeMoveIneffective_Ally', 'PokemonsAbilityMadeMoveIneffective_Wild',
  'PokemonsAbilityMadeMoveIneffective_Foe', 'PokemonsAbilityCuredItsStatus_Ally',
  'PokemonsAbilityCuredItsStatus_Wild', 'PokemonsAbilityCuredItsStatus_Foe',
  'ItSuckedUpTheLiquidOoze', 'PokemonTransformed_Ally', 'PokemonTransformed_Wild',
  'PokemonTransformed_Foe', 'PokemonsAbilityTookTheAttack_Ally',
  'PokemonsAbilityTookTheAttack_Wild', 'PokemonsAbilityTookTheAttack_Foe',
  'PokemonsAbilitySuppressedPokemonsAbility_AllyAlly',
  'PokemonsAbilitySuppressedPokemonsAbility_AllyWild',
  'PokemonsAbilitySuppressedPokemonsAbility_AllyFoe',
  'PokemonsAbilitySuppressedPokemonsAbility_WildAlly',
  'PokemonsAbilitySuppressedPokemonsAbility_WildWild',
  'PokemonsAbilitySuppressedPokemonsAbility_FoeAlly',
  'PokemonsAbilitySuppressedPokemonsAbility_FoeFoe', 'PokemonsAbilityMadeItIneffective_Ally',
  'PokemonsAbilityMadeItIneffective_Wild', 'PokemonsAbilityMadeItIneffective_Foe',
  'PokemonWontFlinchBecauseOfItsAbility_Ally', 'PokemonWontFlinchBecauseOfItsAbility_Wild',
  'PokemonWontFlinchBecauseOfItsAbility_Foe', 'PokemonCuredItsStatusWithItsAbility_Ally',
  'PokemonCuredItsStatusWithItsAbility_Wild', 'PokemonCuredItsStatusWithItsAbility_Foe', '00743',
  '00744', '00745', '00746', '00747', '00748', '00749', 'PokemonsStatRose_Ally',
  'PokemonsStatRose_Wild', 'PokemonsStatRose_Foe', 'PokemonsStatSharplyRose_Ally',
  'PokemonsStatSharplyRose_Wild', 'PokemonsStatSharplyRose_Foe', 'TheItemRaisedPokemonsStat_Ally',
  'TheItemRaisedPokemonsStat_Wild', 'TheItemRaisedPokemonsStat_Foe',
  'TheItemSharplyRaisedPokemonsStat_Ally', 'TheItemSharplyRaisedPokemonsStat_Wild',
  'TheItemSharplyRaisedPokemonsStat_Foe', 'PokemonsStatFell_Ally', 'PokemonsStatFell_Wild',
  'PokemonsStatFell_Foe', 'PokemonsStatHarshlyFell_Ally', 'PokemonsStatHarshlyFell_Wild',
  'PokemonsStatHarshlyFell_Foe', 'PokemonsStatsWontGoAnyHigher_Ally',
  'PokemonsStatsWontGoAnyHigher_Wild', 'PokemonsStatsWontGoAnyHigher_Foe',
  'PokemonsStatsWontGoAnyLower_Ally', 'PokemonsStatsWontGoAnyLower_Wild',
  'PokemonsStatsWontGoAnyLower_Foe', 'ACriticalHit', 'ItsAOneHitKO', 'OneTwoAndPoof',
  'AndDotDotDot', 'Dummy778', 'ItsNotVeryEffective', 'ItsSuperEffective', 'GotAwaySafely',
  'PokemonFledUsingItsItem', 'PokemonFledUsingItsAbility', 'TheWildPokemonFled',
  'PlayerDefeatedLinkTr', 'PlayerDefeatedLinkTr1AndLinkTr2', 'PlayerLostAgainstLinkTr',
  'PlayerLostAgainstLinkTr1AndLinkTr2', 'PlayerDrewAgainstLinkTr',
  'PlayerDrewAgainstLinkTr1AndLinkTr2', 'LinkTrFled', 'LinkTr1AndLinkTr2Fled',
  'NoTheresNoRunningFromATrainerBattle', 'CantEscape2', 'ButNothingHappened', 'ButItFailed',
  'ItHurtItselfInItsConfusion', 'MirrorMoveFailed', 'ItStartedToRain', 'ADownpourStarted',
  'RainContinuesToFall', 'TheDownpourContinues', 'TheRainStopped', 'ASandstormBrewed',
  'TheSandstormRages', 'TheSandstormSubsided', 'TheSunlightTurnedHarsh', 'TheSunlightIsStrong',
  'TheSunlightFaded', 'ItStartedToHail', 'HailContinuesToFall', 'TheHailStopped', 'TheFogIsDeep',
  'ButItFailedToSpitUpAThing', 'ButItFailedToSwallowAThing', 'TheWindTurnedIntoAHeatWave',
  'AllStatChangesWereEliminated', 'CoinsScatteredEverywhere', 'ItWasTooWeakToMakeASubstitute',
  'TheBattlersSharedTheirPain', 'ABellChimed', 'AllPokemonHearingTheSongWillFaintInThreeTurns',
  'TheresNoPPLeftForThisMove', 'ButThereWasNoPPLeftForTheMove', 'PokemonIgnoredOrdersWhileAsleep',
  'PokemonIgnoredOrders', 'PokemonBeganToNap', 'PokemonIsLoafingAround', 'PokemonWontObey',
  'PokemonTurnedAway', 'PokemonPretendedNotToNotice', 'PokemonIsLoafingAround_Ally',
  'PokemonIsLoafingAround_Wild', 'PokemonIsLoafingAround_Foe', 'WillYouSwitchYourPokemon',
  'PokemonLearnedMove2_Ally', 'PokemonLearnedMove_Wild', 'PokemonLearnedMove_Foe',
  'PlayerDefeatedTr', '00840', '00841', '00842', 'Dummy843', 'Dummy844', 'Dummy845', '00846',
  'YoureOutOfSafariBallsNewLineGameOver', 'PlayerThrewASafariBall', 'PokemonIsWatchingCarefully',
  'YoureOutOfSafariBallsGameOver', 'PlayerThrewSomeBaitAtThePokemon', 'PokemonIsEating',
  'PokemonIsBusyEating', 'PlayerThrewMudAtThePokemon', 'PokemonIsAngry',
  'PokemonIsBesideItselfWithAnger', 'PlayerUsedOneItem', 'TrUsedOneItem',
  'TheTrainerBlockedTheBall', 'DontBeAThief', 'ItDodgedTheThrownBallThisPokemonCantBeCaught',
  'YouMissedThePokemon', 'OhNoThePokemonBrokeFree', 'AwwItAppearedToBeCaught', 'AarghAlmostHadIt',
  'ShootItWasSoCloseToo', 'GotchaPokemonWasCaught', 'GiveANicknameToTheCaughtPokemonYesNo',
  'PokemonWasSentToSomeonesPC', 'PokemonWasSentToBebesPC', 'PokemonsDataWasAddedToThePokedex',
  'ItIsRaining', 'ASandstormIsRaging', 'Dummy874', 'PokemonsItemCuredItsParalysis_Ally',
  'PokemonsItemCuredItsParalysis_Wild', 'PokemonsItemCuredItsParalysis_Foe',
  'PokemonsItemCuredItsPoison_Ally', 'PokemonsItemCuredItsPoison_Wild',
  'PokemonsItemCuredItsPoison_Foe', 'PokemonsItemCuredItsBurn_Ally',
  'PokemonsItemCuredItsBurn_Wild', 'PokemonsItemCuredItsBurn_Foe', 'PokemonsItemDefrostedIt_Ally',
  'PokemonsItemDefrostedIt_Wild', 'PokemonsItemDefrostedIt_Foe', 'PokemonsItemWokeItUp_Ally',
  'PokemonsItemWokeItUp_Wild', 'PokemonsItemWokeItUp_Foe',
  'PokemonsItemSnappedItOutOfConfusion_Ally', 'PokemonsItemSnappedItOutOfConfusion_Wild',
  'PokemonsItemSnappedItOutOfConfusion_Foe', 'PokemonCuredItsStatusUsingItsItem_Ally',
  'PokemonCuredItsStatusUsingItsItem_Wild', 'PokemonCuredItsStatusUsingItsItem_Foe',
  'PokemonNormalizedItsStatusUsingItsItem_Ally', 'PokemonNormalizedItsStatusUsingItsItem_Wild',
  'PokemonNormalizedItsStatusUsingItsItem_Foe', 'PokemonRestoredItsHealthUsingItsItem_Ally',
  'PokemonRestoredItsHealthUsingItsItem_Wild', 'PokemonRestoredItsHealthUsingItsItem_Foe',
  'PokemonRestoredMovesPPUsingItsItem_Ally', 'PokemonRestoredMovesPPUsingItsItem_Wild',
  'PokemonRestoredMovesPPUsingItsItem_Foe', 'PokemonRestoredItsStatusUsingItsItem_Ally',
  'PokemonRestoredItsStatusUsingItsItem_Wild', 'PokemonRestoredItsStatusUsingItsItem_Foe',
  'PokemonRestoredALittleHPUsingItsItem_Ally', 'PokemonRestoredALittleHPUsingItsItem_Wild',
  'PokemonRestoredALittleHPUsingItsItem_Foe', 'TheItemAllowsTheUseOfOnlyMove',
  'PokemonHungOnUsingItsItem_Ally', 'PokemonHungOnUsingItsItem_Wild',
  'PokemonHungOnUsingItsItem_Foe', 'WhatPokemonIsEvolving', 'What', 'PokemonIsEvolving',
  'CongratulationsYourPokemonEvolvedIntoPokemon', 'HuhPokemonStoppedEvolving', 'EllipsesEllipses',
  'WhatWillPokemonDo', 'WhatWillPlayerThrow', 'CommunicatingPleaseStandBy', 'Fight', 'Bag',
  'Pokemon', 'Run', 'Cancel', 'Cancel2', 'Cancel3', 'Ball', 'Bait', 'Mud', 'Dummy934', 'Dummy935',
  'Run2', 'CurPPOutOfMaxPP', 'PP', 'WhichMoveShouldBeForgotten', 'Yes', 'No', 'Dummy942',
  'QuitTheBattleYesNo', 'PokemonMaleLevel', 'PokemonFemaleLevel', 'PokemonGenderlessLevel',
  'StatName', 'PlusStatIncrease', 'StatValue', 'SafariBalls', 'SafariBallsLeft', 'Dummy952',
  'PlayerBeatTr1AndTr2', 'Dummy954', 'WouldYouLikeToForfeitTheMatchAndQuitNowYesNo',
  'PlayerForfeitedTheMatch', 'Dummy957', 'Dummy958', '00959', '00960', '00961', '00962', '00963',
  'HealthBoxPokemonName', 'AWildPokemonAppeared', 'AWildPokemonAppeared2',
  'AWildPokemonAndPokemonAppeared', 'AWildPokemonAppearedFromTheTreeYouSlatheredWithHoney',
  'YouAreChallengedByTr', 'YouAreChallengedByLinkTr', 'YouAreChallengedByLinkTr1AndLinkTr2',
  'TrSentOutPokemon', 'TrSentOutPokemon1AndPokemon2', 'LinkTrSentOutPokemon',
  'LinkTrSentOutPokemon1AndPokemon2', 'LinkTr1SentOutPokemon1LinkTr2SentOutPokemon2',
  'LinkTrSentOutPokemon1GoPokemon2', 'GoPokemon1AndPokemon2', 'GoPokemon', 'YoureInChargePokemon',
  'GoForItPokemon', 'YourFoesWeakGetEmPokemon', 'JustALittleMoreHangInTherePokemon',
  'PokemonSwitchOutComeBack', 'PokemonComeBack', 'PokemonOKComeBack', 'PokemonEnoughGetBack',
  'PokemonGoodComeBack', 'TrWithdrewPokemon', 'LinkTrWithdrewPokemon',
  'Tr1SentOutPokemon1Tr2SentOutPokemon2', 'YouAreChallengedByTr1AndTr2',
  'TrSentOutPokemon1GoPokemon2', 'PokemonsStockpiledEffectWoreOff_Ally',
  'PokemonsStockpiledEffectWoreOff_Wild', 'PokemonsStockpiledEffectWoreOff_Foe',
  'GravityIntensified', 'PokemonCouldntStayAirborneBecauseOfGravity_Ally',
  'PokemonCouldntStayAirborneBecauseOfGravity_Wild',
  'PokemonCouldntStayAirborneBecauseOfGravity_Foe', 'PokemonCantUseMoveBecauseOfGravity_Ally',
  'PokemonCantUseMoveBecauseOfGravity_Wild', 'PokemonCantUseMoveBecauseOfGravity_Foe',
  'GravityReturnedToNormal', 'TheHealingWishCameTrue', 'ItBecameCloakedInAMysticalMoonlight',
  'ATailwindStartedBlowing', 'TheTailwindPeteredOut', 'PokemonSwitchedItsAttackAndDefense_Ally',
  'PokemonSwitchedItsAttackAndDefense_Wild', 'PokemonSwitchedItsAttackAndDefense_Foe',
  'PokemonsAbilityWasSuppressed_Ally', 'PokemonsAbilityWasSuppressed_Wild',
  'PokemonsAbilityWasSuppressed_Foe', 'PokemonSwitchedAllAttackChangesWithItsTarget_Ally',
  'PokemonSwitchedAllAttackChangesWithItsTarget_Wild',
  'PokemonSwitchedAllAttackChangesWithItsTarget_Foe',
  'PokemonSwitchedAllDefenseChangesWithItsTarget_Ally',
  'PokemonSwitchedAllDefenseChangesWithItsTarget_Wild',
  'PokemonSwitchedAllDefenseChangesWithItsTarget_Foe', 'PokemonAcquiredAbility_Ally',
  'PokemonAcquiredAbility_Wild', 'PokemonAcquiredAbility_Foe',
  'PokemonSwitchedStatChangesWithTheTarget_Ally', 'PokemonSwitchedStatChangesWithTheTarget_Wild',
  'PokemonSwitchedStatChangesWithTheTarget_Foe', 'PokemonSurroundedItselfWithAVeilOfWater_Ally',
  'PokemonSurroundedItselfWithAVeilOfWater_Wild', 'PokemonSurroundedItselfWithAVeilOfWater_Foe',
  'MoveRestoredPokemonsHP_Ally', 'MoveRestoredPokemonsHP_Wild', 'MoveRestoredPokemonsHP_Foe',
  'PokemonLevitatedOnElectromagnetism_Ally', 'PokemonLevitatedOnElectromagnetism_Wild',
  'PokemonLevitatedOnElectromagnetism_Foe', 'PokemonEvadesGroundMovesWithAbility_Ally',
  'PokemonEvadesGroundMovesWithAbility_Wild', 'PokemonEvadesGroundMovesWithAbility_Foe',
  'PokemonsElectromagnetismWoreOff_Ally', 'PokemonsElectromagnetismWoreOff_Wild',
  'TheElectromagnetismOfPokemonsWoreOff_Foe', 'PokemonBlewAwayMove_Ally',
  'PokemonBlewAwayMove_Wild', 'PokemonBlewAwayMove_Foe', 'PokemonBlewAwayTheDeepFogWithMove_Ally',
  'PokemonBlewAwayTheDeepFogWithMove_Wild', 'PokemonBlewAwayTheDeepFogWithMove_Foe',
  'PokemonFellForTheFeint_Ally', 'PokemonFellForTheFeint_Wild', 'PokemonFellForTheFeint_Foe',
  'PokemonWasPreventedFromHealing_Ally', 'PokemonWasPreventedFromHealing_Wild',
  'PokemonWasPreventedFromHealing_Foe', 'PokemonWasPreventedFromHealingDueToMove_Ally',
  'PokemonWasPreventedFromHealingDueToMove_Wild', 'PokemonWasPreventedFromHealingDueToMove_Foe',
  'PokemonCantUseMoveBecauseOfMove_Ally', 'PokemonCantUseMoveBecauseOfMove_Wild',
  'PokemonCantUseMoveBecauseOfMove_Foe', 'PokemonsMoveWoreOff_Ally', 'PokemonsMoveWoreOff_Wild',
  'PokemonsMoveWoreOff_Foe', 'PoisonSpikesWereScatteredAllAroundYourTeamsFeet',
  'PoisonSpikesWereScatteredAllAroundTheEnemyTeamsFeet',
  'ThePoisonSpikesDisappearedFromAroundYourTeamsFeet',
  'ThePoisonSpikesDisappearedFromAroundTheEnemyTeamsFeet', 'PokemonWentBackToTrainer_Ally',
  'PokemonWentBackToTrainer_Wild', 'PokemonWentBackToTrainer_Foe',
  'PokemonTwistedTheDimensions_Ally', 'PokemonTwistedTheDimensions_Wild',
  'PokemonTwistedTheDimensions_Foe', 'PokemonRestoredTheTwistedDimensions_Ally',
  'PokemonRestoredTheTwistedDimensions_Wild', 'PokemonRestoredTheTwistedDimensions_Foe',
  'TheTwistedDimensionsReturnedToNormal', 'PointedStonesFloatInTheAirAroundYourTeam',
  'PointedStonesFloatInTheAirAroundYourFoesTeam', 'PointedStonesDugIntoPokemon_Ally',
  'PointedStonesDugIntoPokemon_Wild', 'PointedStonesDugIntoPokemon_Foe',
  'PokemonVanishedInstantly_Ally', 'PokemonVanishedInstantly_Wild', 'PokemonVanishedInstantly_Foe',
  'YourTeamsLuckyChantWoreOff', 'TheFoesLuckyChantWoreOff', 'PokemonWasAbility_Ally',
  'PokemonWasAbility_Wild', 'PokemonWasAbility_Foe', 'PokemonIsHurtByItsAbility_Ally',
  'PokemonIsHurtByItsAbility_Wild', 'PokemonIsHurtByItsAbility_Foe',
  'PokemonMaxedItsStatWithAbility_Ally', 'PokemonMaxedItsStatWithAbility_Wild',
  'PokemonMaxedItsStatWithAbility_Foe', 'PokemonLostSomeHPBecauseOfItsAbility_Ally',
  'PokemonLostSomeHPBecauseOfItsAbility_Wild', 'PokemonLostSomeHPBecauseOfItsAbility_Foe',
  'PokemonWasHurtByPokemonsAbility_AllyAlly', 'PokemonWasHurtByPokemonsAbility_WildAlly',
  'PokemonWasHurtByPokemonsAbility_FoeAlly', 'PokemonWasHurtByPokemonsAbility_AllyWild',
  'PokemonWasHurtByPokemonsAbility_WildWild', 'PokemonWasHurtByPokemonsAbility_AllyFoe',
  'PokemonWasHurtByPokemonsAbility_FoeFoe', 'PokemonsAbilityMadeItShudder_Ally',
  'PokemonsAbilityMadeItShudder_Wild', 'PokemonsAbilityMadeItShudder_Foe',
  'PokemonsAbilityAlertedItToMove_Ally', 'PokemonsForewarnAlertedItToMove_Wild',
  'PokemonsForewarnAlertedItToMove_Foe', 'PokemonCantGetItGoingBecauseOfItsAbility_Ally',
  'PokemonCantGetItGoingBecauseOfItsAbility_Wild', 'PokemonCantGetItGoingBecauseOfItsAbility_Foe',
  'PokemonFinallyGotItsActTogether_Ally', 'PokemonFinallyGotItsActTogether_Wild',
  'PokemonFinallyGotItsActTogether_Foe', 'PokemonFriskedItsFoeAndFoundOneItem_Ally',
  'PokemonFriskedItsFoeAndFoundOneItem_Wild', 'PokemonFriskedItsFoeAndFoundOneItem_Foe',
  'PokemonIsTormentedByPokemonsAbility_AllyAlly', 'PokemonIsTormentedByPokemonsAbility_WildAlly',
  'PokemonIsTormentedByPokemonsAbility_FoeAlly', 'PokemonIsTormentedByPokemonsAbility_AllyWild',
  'PokemonIsTormentedByPokemonsAbility_WildWild', 'PokemonIsTormentedByPokemonsAbility_AllyFoe',
  'PokemonIsTormentedByPokemonsAbility_FoeFoe', '01128', '01129', '01130',
  'TheItemWeakenedMovesPower', 'PokemonIsHurtByItsItem_Ally', 'PokemonIsHurtByItsItem_Wild',
  'PokemonIsHurtByItsItem_Foe', 'PokemonCantUseItemsAnymore_Ally',
  'PokemonCantUseItemsAnymore_Wild', 'PokemonCantUseItemsAnymore_Foe',
  'PokemonCanUseItemsAgain_Ally', 'PokemonCanUseItemsAgain_Wild', 'PokemonCanUseItemsAgain_Foe',
  'PokemonStoleAndAteItsFoesItem_Ally', 'PokemonStoleAndAteItsFoesItem_Wild',
  'PokemonStoleAndAteItsFoesItem_Foe', 'PokemonFlungItsItem_Ally', 'PokemonFlungItsItem_Wild',
  'PokemonFlungItsItem_Foe', 'PokemonsAbilityMadeTheItemIneffective_Ally',
  'PokemonsAbilityMadeTheItemIneffective_Wild', 'PokemonsAbilityMadeTheItemIneffective_Foe',
  'PokemonsItemInfatuatedPokemon_AllyAlly', 'PokemonsItemInfatuatedPokemon_AllyWild',
  'PokemonsItemInfatuatedPokemon_AllyFoe', 'PokemonsItemInfatuatedPokemon_WildAlly',
  'PokemonsItemInfatuatedPokemon_WildWild', 'PokemonsItemInfatuatedPokemon_FoeAlly',
  'PokemonsItemInfatuatedPokemon_FoeFoe',
  'PokemonsBoostedTheAccuracyOfItsNextMoveUsingItsItem_Ally',
  'PokemonsBoostedTheAccuracyOfItsNextMoveUsingItsItem_Wild',
  'PokemonsBoostedTheAccuracyOfItsNextMoveUsingItsItem_Foe',
  'PokemonIsHurtByPokemonsItem_AllyAlly', 'PokemonIsHurtByPokemonsItem_AllyWild',
  'PokemonIsHurtByPokemonsItem_AllyFoe', 'PokemonIsHurtByPokemonsItem_WildAlly',
  'PokemonIsHurtByPokemonsItem_WildWild', 'PokemonIsHurtByPokemonsItem_FoeAlly',
  'PokemonIsHurtByPokemonsItem_FoeFoe', 'WhoaAWildPokemonCameCharging',
  'PokemonWasBadlyPoisonedByTheItem_Ally', 'PokemonWasBadlyPoisonedByTheItem_Wild',
  'PokemonWasBadlyPoisonedByTheItem_Foe', 'PokemonGotABurnFromTheItem_Ally',
  'PokemonGotABurnFromTheItem_Wild', 'PokemonGotABurnFromTheItem_Foe',
  'PokemonWasTransferredToBoxInSomeonesPC', 'PokemonWasTransferredToBoxInBebesPC',
  'BoxInSomeonesPCIsFullPokemonWasTransferredToOtherBoxInstead',
  'BoxInBebesPCIsFullPokemonWasTransferredToOtherBoxInstead', 'PokemonWantsToLearnMove',
  'ButPokemonCantLearnMoreThanFourMoves2', 'MakeItForgetAnotherMoveYesNo', 'ForgetAMove',
  'KeepOldMoves', 'WhichMoveShouldBeForgotten2', 'WellThen', 'ShouldPokemonGiveUpOnLearningMove',
  'GiveUpOnMove', 'DontGiveUpOnMove', 'PokemonDidNotLearnMove2', 'BattleOneTwoAndPoof',
  'BattlePokemonForgotHowToUseMove', 'BattleAndDotDotDot', 'BattlePokemonLearnedMove',
  'PokemonWantsToLearnTheMove', 'HoweverPokemonAlreadyKnowsFourMoves', 'ShouldAMoveBeDeleted',
  'WhichMoveShouldBeForgotten3', 'StopTryingToTeachMove', 'PokemonDidNotLearnTheMove',
  'EvolutionOneTwoAndPoof', 'PokemonForgotHowToUseMove', 'EvolutionAndDotDotDot',
  'EvolvedPokemonLearnedMove', 'PokemonsStatRose', 'YourTeamBecameShroudedInAWhiteFog',
  'PokemonIsGettingPumped', 'UsedTheItem', 'PokemonWasCuredOfItsPoisoning',
  'PokemonWasCuredOfParalysis', 'PokemonsBurnWasHealed', 'PokemonWokeUp', 'PokemonWasThawedOut',
  'PokemonSnappedOutOfItsConfusion', 'PokemonGotOverItsInfatuation',
  'PokemonsHPWasRestoredByXPoints', 'SwitchPokemon', 'KeepBattling', 'UseNextPokemon', 'Flee',
  '01219', 'ParkBalls', 'ParkBallsLeft', 'WhatWillPlayerDo', 'BallPalPark', 'RunPalPark',
  'PokemonComeBackPalPark', 'AllRightIGotItsHPDownTimeToThrowAPokeBall',
  'OKTheGotIsHPDownTimeItsReadyForAPokeBall', '01228', 'PokemonGotOverItsStatusTrouble',
  'TheTailwindBlewFromBehindYourTeam', 'TheTailwindBlewFromBehindTheFoe',
  'YourTeamsTailwindPeteredOut', 'TheFoesTailwindPeteredOut', 'ButThereWasNoTarget',
  'ItFailedToAffectPokemon_Ally', 'ItFailedToAffectPokemon_Wild', 'ItFailedToAffectPokemon_Foe',
  'PokemonIsExertingItsAbility_Ally', 'PokemonIsExertingItsAbility_Wild',
  'PokemonIsExertingItsAbility_Foe', 'TheLuckyChantShieldedYourTeamFromCriticalHits',
  'TheLuckyChantShieldedTheFoeFromCriticalHits', 'ItBrokeThroughPokemonsProtection_Ally',
  'ItBrokeThroughPokemonsProtection_Wild', 'ItBrokeThroughPokemonsProtection_Foe',
  'AWildPokemonAppeared3', 'PokemonBecameTrappedBySwirlingMagma_Ally',
  'PokemonBecameTrappedBySwirlingMagma_Wild', 'PokemonBecameTrappedBySwirlingMagma_Foe',
  'PokemonBecameHealthy', 'PokemonBecameFullyChargedDueToItsItem_Ally',
  'PokemonBecameFullyChargedDueToItsItem_Wild', 'PokemonBecameFullyChargedDueToItsItem_Foe',
  'PokemonsItemLetItMoveFirst_Ally', 'PokemonsItemLetItMoveFirst_Wild',
  'PokemonsItemLetItMoveFirst_Foe', 'PokemonsTauntWoreOff_Ally', 'PokemonsTauntWoreOff_Wild',
  'PokemonsTauntWoreOff_Foe', 'Stop', 'PlaybackPaused', 'PleaseWait', 'DataIsCorrupted',
  'PlaybackCanceled', 'BattleIsTooLong', 'PlaybackCanceled2', 'TheDimensionsBecameDistorted',
  'TheDistortionWorldsPokemonAppeared',
]

const BATTLEMESSAGE_AT = new Map(BATTLE_STRING_ORDER.map((id, i) => [id, i]))

/**
 * 배틀 글의 이름 → 줄 번호. 없는 이름이면 던진다.
 *
 * 조용히 -1을 내면 그 번호로 뱅크를 집었을 때 **뒤에서 세어** 엉뚱한 글이 뜬다
 */
export function battleMessage(name: string): number {
  const at = BATTLEMESSAGE_AT.get(name)
  if (at === undefined) throw new Error(`배틀 글에 그런 이름이 없다: ${name}`)
  return at
}

/** `battle_bag` (us 2) 뱅크 안의 줄 순서. 자리가 곧 줄 번호다 */
export const BATTLE_BAG_ORDER: readonly string[] = [
  'MenuTitleHPPP', 'MenuTitleRestore', 'MenuTitleStatus', 'MenuTitleHealers',
  'pl_msg_00000002_00004', 'pl_msg_00000002_00005', 'MenuTitleBattleItems', 'MenuTitlePokeBalls',
  'ItemUsedLast', 'PocketSlot1ItemName', 'PocketSlot1ItemAmount', 'PocketSlot2ItemName',
  'PocketSlot2ItemAmount', 'PocketSlot3ItemName', 'PocketSlot3ItemAmount', 'PocketSlot4ItemName',
  'PocketSlot4ItemAmount', 'PocketSlot5ItemName', 'PocketSlot5ItemAmount', 'PocketSlot6ItemName',
  'PocketSlot6ItemAmount', 'pl_msg_00000002_00021', 'PocketNameHPPP', 'PocketNameRestore',
  'PocketNameStatus', 'PocketNameHealers', 'PocketNamePokeBalls', 'PocketNameBattleItems',
  'PocketPageDivider', 'PocketCurrentPage', 'PocketPageNum', 'Use', 'pl_msg_00000002_00032',
  'pl_msg_00000002_00033', 'ItemHasNoUse', 'pl_msg_00000002_00035', 'pl_msg_00000002_00036',
  'pl_msg_00000002_00037', 'pl_msg_00000002_00038', 'pl_msg_00000002_00039',
  'pl_msg_00000002_00040', 'pl_msg_00000002_00041', 'pl_msg_00000002_00042',
  'pl_msg_00000002_00043', 'CantUseBallTwoPokemon', 'CantUseBallNoRoomLeft',
  'EmbargoBlockingItemUse', 'CantUseBallPokemonHidden', 'CantUseBallPokemonSubstituted',
]

const BAGMESSAGE_AT = new Map(BATTLE_BAG_ORDER.map((id, i) => [id, i]))

/**
 * 배틀 안 가방의 이름 → 줄 번호. 없는 이름이면 던진다.
 *
 * 조용히 -1을 내면 그 번호로 뱅크를 집었을 때 **뒤에서 세어** 엉뚱한 글이 뜬다
 */
export function bagMessage(name: string): number {
  const at = BAGMESSAGE_AT.get(name)
  if (at === undefined) throw new Error(`배틀 안 가방에 그런 이름이 없다: ${name}`)
  return at
}

/** `battle_party` (us 3) 뱅크 안의 줄 순서. 자리가 곧 줄 번호다 */
export const BATTLE_PARTY_ORDER: readonly string[] = [
  'PartyPokemon1Name', 'PartyPokemon2Name', 'PartyPokemon3Name', 'PartyPokemon4Name',
  'PartyPokemon5Name', 'PartyPokemon6Name', 'ChooseAPokemon', 'UseOnWhichPokemon',
  'PokemonAbilityName', 'PokemonHeldItemName', 'pl_msg_00000003_00010', 'pl_msg_00000003_00011',
  'pl_msg_00000003_00012', 'pl_msg_00000003_00013', 'PokemonPPLabel', 'ShiftButton', 'MaleIcon',
  'FemaleIcon', 'SummaryButton', 'CheckMovesButton', 'PokemonNoItemHeld', 'pl_msg_00000003_00021',
  'pl_msg_00000003_00022', 'PokemonLevelLabel', 'PokemonLevelValue', 'PokemonExpToNextLevelLabel',
  'PokemonExpToNextLevelValue', 'pl_msg_00000003_00027', 'PokemonHPStatLabel',
  'PokemonHPStatValue', 'PokemonMaxHPStatValue', 'PokemonHPStatDivider', 'PokemonAttackStatLabel',
  'PokemonAttackStatValue', 'PokemonDefenseStatLabel', 'PokemonDefenseStatValue',
  'PokemonSpAtkStatLabel', 'PokemonSpAtkStatValue', 'PokemonSpDefStatLabel',
  'PokemonSpDefStatValue', 'PokemonSpeedStatLabel', 'PokemonSpeedStatValue',
  'pl_msg_00000003_00042', 'MovePPLabel', 'MoveCurrentPP', 'MoveMaxPP', 'MovePPDivider',
  'pl_msg_00000003_00047', 'MovePowerLabel', 'MovePowerValue', 'MoveStatNoValue',
  'MoveAccuracyLabel', 'MoveAccuracyValue', 'MoveCategoryLabel', 'MoveCategoryPhysical',
  'MoveCategoryStatus', 'MoveCategorySpecial', 'AppealPtsLabel', 'ForgetMoveButton',
  'CancelMoveButton', 'HMMovesCantBeForgotten', 'Move1Name', 'pl_msg_00000003_00062',
  'pl_msg_00000003_00063', 'Move2Name', 'pl_msg_00000003_00065', 'pl_msg_00000003_00066',
  'Move3Name', 'pl_msg_00000003_00068', 'pl_msg_00000003_00069', 'Move4Name',
  'pl_msg_00000003_00071', 'pl_msg_00000003_00072', 'MoveToLearnName', 'pl_msg_00000003_00074',
  'pl_msg_00000003_00075', 'CantSwitchWithPokemonAlreadyInBattle', 'CantSwitchWithFaintedPokemon',
  'CantSwitchPokemon', 'CantSwitchWithEgg', 'CantSwitchWithPartnersPokemon',
  'ItemWontHaveAnyEffect', 'ItemRestoredHealth', 'ItemCuredPoisoning', 'ItemCuredParalysis',
  'ItemCuredBurn', 'ItemCuredFreeze', 'ItemRestoredPP', 'ItemRevivedPokemon',
  'ItemCuredMultipleStatuses', 'ItemCuredConfusion', 'ItemCuredInfatuation', 'ItemCuredSleep',
  'CantSwitchWithAlreadySelectedPokemon', 'RestoreWhichMove', 'EmbargoPreventsItemUse',
]

const PARTYMESSAGE_AT = new Map(BATTLE_PARTY_ORDER.map((id, i) => [id, i]))

/**
 * 배틀 안 파티의 이름 → 줄 번호. 없는 이름이면 던진다.
 *
 * 조용히 -1을 내면 그 번호로 뱅크를 집었을 때 **뒤에서 세어** 엉뚱한 글이 뜬다
 */
export function partyMessage(name: string): number {
  const at = PARTYMESSAGE_AT.get(name)
  if (at === undefined) throw new Error(`배틀 안 파티에 그런 이름이 없다: ${name}`)
  return at
}
