// 플래티넘 트레이너 갈래표 (DATA.md §2.16)
//
// ⚠️ **손으로 고치지 않는다.** `pnpm gen:trainerClasses`가 디컴프에서 다시
// 만든다 (`tools/extract/trainerClassModule.cjs`).
//
// **표지 게임 자료가 아니다** — 이름표와 색인 번호와 개수뿐이다 (COPYRIGHT.md §2).

/** 갈래 이름. 줄 번호가 곧 갈래 번호다 (`generated/trainer_classes.txt`) */
export const TRAINER_CLASS_NAMES: readonly string[] = [
  'PLAYER_MALE',
  'PLAYER_FEMALE',
  'YOUNGSTER',
  'LASS',
  'CAMPER',
  'PICNICKER',
  'BUG_CATCHER',
  'AROMA_LADY',
  'TWINS',
  'HIKER',
  'BATTLE_GIRL',
  'FISHERMAN',
  'CYCLIST_MALE',
  'CYCLIST_FEMALE',
  'BLACK_BELT',
  'ARTIST',
  'BREEDER_MALE',
  'BREEDER_FEMALE',
  'COWGIRL',
  'JOGGER',
  'POKEFAN_MALE',
  'POKEFAN_FEMALE',
  'POKE_KID',
  'YOUNG_COUPLE',
  'ACE_TRAINER_MALE',
  'ACE_TRAINER_FEMALE',
  'WAITRESS',
  'VETERAN',
  'NINJA_BOY',
  'DRAGON_TAMER',
  'BIRD_KEEPER',
  'DOUBLE_TEAM',
  'RICH_BOY',
  'LADY',
  'GENTLEMAN',
  'SOCIALITE',
  'BEAUTY',
  'COLLECTOR',
  'POLICEMAN',
  'RANGER_MALE',
  'RANGER_FEMALE',
  'SCIENTIST',
  'SWIMMER_MALE',
  'SWIMMER_FEMALE',
  'TUBER_MALE',
  'TUBER_FEMALE',
  'SAILOR',
  'SIS_AND_BRO',
  'RUIN_MANIAC',
  'PSYCHIC_MALE',
  'PSYCHIC_FEMALE',
  'PI',
  'GUITARIST',
  'ACE_TRAINER_SNOW_MALE',
  'ACE_TRAINER_SNOW_FEMALE',
  'SKIER_MALE',
  'SKIER_FEMALE',
  'ROUGHNECK',
  'CLOWN',
  'WORKER',
  'SCHOOL_KID_MALE',
  'SCHOOL_KID_FEMALE',
  'LEADER_ROARK',
  'RIVAL',
  'LEADER_BYRON',
  'ELITE_FOUR_AARON',
  'ELITE_FOUR_BERTHA',
  'ELITE_FOUR_FLINT',
  'ELITE_FOUR_LUCIAN',
  'CHAMPION_CYNTHIA',
  'BELLE_AND_PA',
  'RANCHER',
  'COMMANDER_MARS',
  'GALACTIC_GRUNT_MALE',
  'LEADER_GARDENIA',
  'LEADER_WAKE',
  'LEADER_MAYLENE',
  'LEADER_FANTINA',
  'LEADER_CANDICE',
  'LEADER_VOLKNER',
  'PARASOL_LADY',
  'WAITER',
  'INTERVIEWERS',
  'CAMERAMAN',
  'REPORTER',
  'IDOL',
  'GALACTIC_BOSS',
  'COMMANDER_JUPITER',
  'COMMANDER_SATURN',
  'GALACTIC_GRUNT_FEMALE',
  'TRAINER_CHERYL',
  'TRAINER_RILEY',
  'TRAINER_MARLEY',
  'TRAINER_BUCK',
  'TRAINER_MIRA',
  'DP_PLAYER_MALE',
  'DP_PLAYER_FEMALE',
  'TOWER_TYCOON',
  'MAID',
  'HALL_MATRON',
  'FACTORY_HEAD',
  'ARCADE_STAR',
  'CASTLE_VALET',
  'DP_PLAYER_MALE_2',
  'DP_PLAYER_FEMALE_2',
]

/**
 * 오버월드 그림 → 트레이너 갈래.
 *
 * 짐작이 아니라 **게임이 실제로 세운 짝**이다 — 배치표의 트레이너 NPC가 어느
 * 갈래로 싸우는지 세었다. 한 그림에 갈래가 여럿 걸리는 자리가 있어서
 * (`ACE_TRAINER_M` 하나로 에이스 트레이너·용사냥꾼·포켓몬레인저가 다 선다)
 * 제일 많이 선 것을 적고 몇 대 몇이었는지도 남긴다. 과반이 아니면 안 적는다.
 *
 * `[그림 번호, 트레이너 갈래, 그 갈래로 선 배치 수, 전체 배치 수]`
 */
export type SpriteClassRow = readonly [number, number, number, number]

export const SPRITE_TRAINER_CLASS: readonly SpriteClassRow[] = [
  [1, 28, 10, 10],
  [2, 8, 6, 6],
  [3, 60, 3, 3],
  [4, 2, 12, 12],
  [5, 6, 4, 4],
  [6, 3, 8, 8],
  [7, 10, 3, 3],
  [8, 61, 3, 3],
  [9, 16, 2, 3],
  [10, 52, 4, 5],
  [11, 24, 23, 42],
  [13, 36, 3, 4],
  [14, 25, 23, 38],
  [15, 20, 1, 1],
  [16, 21, 1, 1],
  [17, 27, 8, 8],
  [19, 37, 8, 8],
  [20, 9, 13, 13],
  [29, 41, 5, 5],
  [31, 57, 1, 1],
  [32, 55, 4, 4],
  [33, 56, 4, 4],
  [34, 38, 6, 6],
  [36, 34, 1, 1],
  [37, 35, 1, 1],
  [38, 12, 4, 4],
  [39, 13, 4, 4],
  [40, 59, 12, 12],
  [41, 70, 2, 3],
  [42, 70, 2, 3],
  [44, 15, 1, 1],
  [45, 19, 5, 5],
  [46, 42, 16, 16],
  [47, 43, 17, 17],
  [48, 45, 4, 4],
  [49, 44, 4, 4],
  [50, 48, 7, 7],
  [51, 14, 23, 23],
  [52, 4, 8, 8],
  [53, 5, 8, 8],
  [54, 11, 17, 17],
  [55, 80, 2, 2],
  [56, 46, 7, 7],
  [60, 26, 1, 1],
  [62, 32, 2, 3],
  [63, 33, 1, 1],
  [68, 53, 6, 6],
  [69, 54, 6, 6],
  [71, 22, 3, 3],
  [124, 73, 21, 21],
  [125, 89, 13, 13],
]
